### PR TITLE
Repo cleanup

### PR DESCRIPTION
**Pull request by yenanw**
- Removed `.eslintcache` and `/.idea`.
- Updated `.gitignore` so that most auto-generated files should be covered.
- Changed the `npm start` script in `package.json`. Previously it used a `del` command which was not available on linux and therefore you couldn't start the app on linux. Now that `.eslintcache` is removed, that command is no longer needed.
- Updated the `README.md` so that it refers to the backend repository.

### CODE REVIEW

**Comment by gabrieloldaccount** [comment]
Sorry for the .eslintcache. It's a common issue that it gets re-generated all the time and conflict with other local versions. Del was a quick fix but we can also just ignore it in all pushes.

**Comment by Puh00** [comment]
@yenanw just got rejected

**Comment by yenanw** [comment]
aite wait

**Comment by gabrieloldaccount** [comment]
Sorry for the .eslintcache. It's a common issue that it gets re-generated all the time and conflict with other local versions. Del was a quick fix but we can also just ignore it in all pushes.

And sorry for the mistaken closing. I wanted to merge it.

**Pull request merged**
