### PR TITLE
Refactor/structure eslint

### LINKED ISSUE #27: Duplicate product-rows on create-invoice page
* Squash duplicate rows into a single row

### LINKED ISSUE #31: Fix .dot position
.dot in navbar is unaligned

### PR DESCRIPTION
**Pull request by Puh00**
## Changes:
* Restructured files
  * Deleted unused files
* Fixed CSS bug in create-invoice
* Fixed duplicate rows bug, see #27 
* Fixed dot position which is caused by this PR, see #31 
* Resolved all ESLint warnings

## New structure of the project
📁 src\
&nbsp;&nbsp;📁 assets\
&nbsp;&nbsp;📁 components\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;📁 header\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;📁 home\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;📁 invoices\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;📁 pdf\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;📁 table-items\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;📁 products\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;📁 util\
&nbsp;&nbsp;📁 services\
&nbsp;&nbsp;📁 styles

### Where to put stuff
* assets:= images
* components:= all of the components
  * please put new components in a suitable folder (or create a new folder)
* services:= bridge between frontend and backend
* styles:= css stuff

### CODE REVIEW

**Review by Puh00 — COMMENTED** [review]
Hmm looks good to me if I'd say so

**Comment by yenanw** [comment]
> 
> 
> Hmm looks good to me if I'd say so

???

**Review by hedy-99 — APPROVED** [review]
Looks ok

**Review by ElinFredrik — APPROVED** [review]
Looks good :)

**Pull request merged**
